### PR TITLE
feat: allow custom claims in login form

### LINKED ISSUE #112: Support other claims in login form
Hi there,

Thanks a lot for creating this project. I'm currently playing with the stand-alone docker image as a lightweight alternative to a full OAuth2 server.

The current request mapping lets you specify different claims to be returned based on request parameters, but I could not find a way to define different claims based on the information in the "login" form, subject or acr. (Please let me know if I missed something). 
I've looked a bit through the source code and from what I saw this isn't easy to implement since the focus of this project is unit testing and the stand-alone server was build around it.

That said, since the login form already offers an easy way to set `sub` and `acr`, having a way to specify more claims there, would work perfectly for me. I've played a bit with the code and came up with this on the UI side:

Screenshot
 
and this change here https://github.com/navikt/mock-oauth2-server/blob/master/src/main/kotlin/no/nav/security/mock/oauth2/grant/AuthorizationCodeGrantHandler.kt#L93 for the `LoginOAuth2TokenCallback`

```kotlin
override fun addClaims(tokenRequest: TokenRequest): Map<String, Any> =
    OAuth2TokenCallback.addClaims(tokenRequest).toMutableMap().apply {
      login.claims?.let { // Renamed login.acr to login.claims
          jsonMapper.readTree(it)
              .fields()
              .forEach { field -> put(field.key, jsonMapper.readValue(field.value.toString())) }
          }
    }
```

What do you think about this? Would you consider this direction an improvement?
If yes, I could go forward with this and open a PR for detailed feedback.

### PR DESCRIPTION
**Pull request by jp7677**
Replace the acr field in the login form with a text area that is supposed to be filled with a JSON structure containing one or more claims.

This implements https://github.com/navikt/mock-oauth2-server/issues/112

### CODE REVIEW

**Comment by tommytroen** [comment]
@jp7677 direction looks good to me. Let me know when the PR is ready for review.

**Review by tommytroen — COMMENTED** [review]
@jp7677 Thank you very much for your contribution, the PR looks good to me. Left a few minor comments.

**Comment by tommytroen** [comment]
@jp7677 just released https://github.com/navikt/mock-oauth2-server/releases/tag/0.3.6 with your PR (give it a couple of minutes for the CI to finish). Let me know if you have any issues.

**Comment by jp7677** [comment]
Thanks a lot for the fast release, works as intended!

**Pull request merged**
