### PR TITLE
add: example of how we can document the api 

### LINKED ISSUE #268: doc: Add KDoc and dokka
No JavaDocs on any of the methods in MockOAuth2Server, which unfortunately makes this library nearly unusable, unless one study its source code @arcuri82

### PR DESCRIPTION
**Pull request by ybelMekk**
with dokka and kdoc and GitHub flavored markdown (gfm)

This can be done with HTML format also if preferred.

The action runs on publish and updates doc folder to contain the latest release documentation updates.

Also changed all workflows with gradle cache setup, to use action `setup-java` built-in cache instead of separate action.

Please add documentation before approve/merge, as this is lacking for the library ~due to some developer `laziness` 😄~

Also, checkout the branch, and run `./gradlew dokkaHtm` or `./gradlew dokkaGtm` to explore the result.

### CODE REVIEW

**Comment by tronghn** [comment]
Looks good to me.

Dokka also appears to have a `dokkaJavadoc` task as well - does this run as part of the `publish` task? We should probably consider setting up a javadoc so that releases to Maven Central also includes the documentation.

**Comment by ybelMekk** [comment]
> Looks good to me.
> 
> Dokka also appears to have a `dokkaJavadoc` task as well - does this run as part of the `publish` task? We should probably consider setting up a javadoc so that releases to Maven Central also includes the documentation.

good as @tronghn . Sounds like a better solution, if we go for release of documentation.

**Comment by tronghn** [comment]
I mean, we can have both solutions - they both stem from the same source anyway 😄

**Comment by ybelMekk** [comment]
🤩

**Comment by ybelMekk** [comment]
@tronghn please add sum commits, if you have a good one?

**Comment by ybelMekk** [comment]
seems like a good start to me, if we want to include this? @tommytroen , @jksolbakken @tronghn ?

**Review by jksolbakken — APPROVED** [review]

**Pull request merged**
