### PR TITLE
#691 `OAuth2TokenProvider` should allow dynamic `systemTime`

### LINKED ISSUE #691: `OAuth2TokenProvider` should allow a flexible `systemTime`
A global fixed `systemTime` is not enough to write tests in practice at all.

I propose to change the current implementation

```
class OAuth2TokenProvider(
        private val keyProvider: KeyProvider = KeyProvider(),
        val systemTime: Instant? = null,
    )
```

to the backward compatible implemenation like below

```
typealias TimeProvider = () -> Instant?

class OAuth2TokenProvider(
  private val keyProvider: KeyProvider = KeyProvider(),
  private val timeProvider: TimeProvider,
) {
  val systemTime
    get() = timeProvider()

  @JvmOverloads
  constructor(
    keyProvider: KeyProvider = KeyProvider(),
    systemTime: Instant? = null,
  ) : this(keyProvider, { systemTime })
}
```

I am not sure if we need to adapt anywhere else (ex. `OAuth2TokenProviderDeserializer`) with this change or not.

### PR DESCRIPTION
**Pull request by xuanswe**
Implement #691

### CODE REVIEW

**Comment by xuanswe** [comment]
Missing tests

**Review by ybelMekk — CHANGES_REQUESTED** [review]
just do the formating and I will merge.

**Comment by xuanswe** [comment]
> just do the formating and I will merge.

@ybelMekk Done :)

**Review by ybelMekk — APPROVED** [review]
lgtm

**Pull request merged**
