### PR TITLE
chore: bumped java to 21

### PR DESCRIPTION
**Pull request by MikAoJk**

### CODE REVIEW

**Comment by MikAoJk** [comment]
@ybelMekk

**Comment by MikAoJk** [comment]
@navikt/pig-sikkerhet

**Review by ybelMekk — APPROVED** [review]
Hello! Could be potensial breaking change this?

**Comment by MikAoJk** [comment]
> Hello! Could be potensial breaking change this?

Should not be a breaking change, but cannot say it for sure

**Pull request closed without merging**
