### PR TITLE
Update to use ktor 2.0.1

### PR DESCRIPTION
**Pull request by MikAoJk**

### CODE REVIEW

**Comment by MikAoJk** [comment]
plz run test, localy there are some tests that fails, not sure if local issue or not

**Review by ybelMekk — CHANGES_REQUESTED** [review]
Hello. Jawk

Tests runs fine locally.

But i get som deprecation notice:
```
mock-oauth2-server/src/test/kotlin/examples/kotlin/ktor/resourceserver/OAuth2ResourceServerAppTest.kt: (18, 13): 
withTestApplication(Application.() -> Unit, TestApplicationEngine.() -> R): 
R' is deprecated. Please use new `testApplication` API: https://ktor.io/docs/migrating-2.html#testing-api
```

also (35, 13) and (55, 13)

**Comment by ybelMekk** [comment]
> Yes, The withTestApplication/withApplication functions are replaced with a new testApplication function. Should we include the change in this PR or in a new one?
> 
> Ref: https://ktor.io/docs/migrating-2.html#testing-api

I recon it could be included in this PR, as it is spinns of after the update to ktor 2.0.1.

**Comment by MikAoJk** [comment]
@ybelMekk i fixed the usage of withTestApplication due to deprecation, can you run the tests now, and see if its all good?

**Review by ybelMekk — CHANGES_REQUESTED** [review]
Tests run 🆗 

@MikAoJk did you run `formatKotlin` ?

**Comment by MikAoJk** [comment]
no i will do

**Comment by MikAoJk** [comment]
My local issue was i had this in the /etc/hosts file:
127.0.0.1 view-localhost
127.0.0.1 localhost

i need to remove the view-localhost and the the tests worked

**Comment by MikAoJk** [comment]
@ybelMekk formatKotlin done

**Review by ybelMekk — APPROVED** [review]

**Comment by ybelMekk** [comment]
@tommytroen  👀?

**Review by tommytroen — APPROVED** [review]
lgtm. 🚢

**Pull request merged**
