### PR TITLE
feat: algorithm to initial keys

### LINKED ISSUE #247: Add alg parameter to initial keys
Some clients (google-oauth-client) seem to expect the `alg` parameter when parsing jwks key endpoints (even though they are optional). Can we add those to the initial keys resources to expand compatibility?

### PR DESCRIPTION
**Pull request by ybelMekk**

### CODE REVIEW

**Comment by loosebazooka** [comment]
It looks like this doesn't affect the keys being pulled in via the initial keys file? Those are parsed directly in https://github.com/navikt/mock-oauth2-server/blob/master/src/main/kotlin/no/nav/security/mock/oauth2/token/KeyProvider.kt#L57

Do the init key files need to have the algorithm in them?
mock-oauth2-server-keys.json
mock-oauth2-server-keys-ec.json

**Comment by loosebazooka** [comment]
Adding those into the json files seems to work for me, but I don't fully comprehend the consequence of that or if all the RSA keys in there are actually RS256, and the EC ones are ES256?

**Comment by ybelMekk** [comment]
😅 I did not think about the files.. but yes, should be ok, adding a commit!

**Comment by ybelMekk** [comment]
seems like position of "alg" in the jwk mathers for nimbus to be able read the key properly. 

Should be ok now @loosebazooka 

👍🏾

**Comment by loosebazooka** [comment]
I'll try it out!

**Review by loosebazooka — APPROVED** [review]
lgtm, works in my tests :D

**Comment by ybelMekk** [comment]
> lgtm, works in my tests :D

Great! 

:ship: it

**Review by tommytroen — APPROVED** [review]
LGTM

**Pull request merged**
