### PR TITLE
feat: add code to allow password type grant for tokens

### PR DESCRIPTION
**Pull request by nihar**
- add code to enable password grants
- add unit tests for password grant workflow

### CODE REVIEW

**Comment by ybelMekk** [comment]
Hello.

Thank you for contributing to the server, and I’m happy to see a fresh PR coming in.

I can se from de workflow run that you have som Kotlin lint problems in the code. Fix ‘‘em and re run 🏃‍♀️ 

cheers

**Comment by nihar** [comment]
> Hello.
> 
> Thank you for contributing to the server, and I’m happy to see a fresh PR coming in.
> 
> I can see from de workflow run that you have som Kotlin lint problems in the code. Fix ‘‘em and re run 🏃‍♀️
> 
> cheers

Fixed listing in the latest commit

**Comment by ybelMekk** [comment]
Hello.

And thanks for fixing the lint.

Taking this: [Remove Password Grant from Oauth ](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-13#section-3.4) in consideration I am not sure we want to implement this in to the server

```
The resource owner password credentials grant MUST NOT be used.  This
   grant type insecurely exposes the credentials of the resource owner
   to the client.  Even if the client is benign, this results in an
   increased attack surface (credentials can leak in more places than
   just the AS) and users are trained to enter their credentials in
   places other than the AS.
``` 

@jksolbakken, @tronghn and @tommytroen ?

**Comment by nihar** [comment]
Mostly, I submitted this PR because we use this flow for _some_ internal apps - figured it might be helpful for others if they use this flow internally. Please feel free to close the PR if this should not be added

**Comment by ybelMekk** [comment]
Have you considered https://www.rfc-editor.org/rfc/rfc8693.html ? For “Internal” applications :) take a look at: https://github.com/nais/tokendings (advertising 🤓😊)

**Comment by nihar** [comment]
We are writing newer apps with the Authorization Code workflow but have to still maintain a lot of legacy apps with the ROPC flow for the next couple of years.

**Comment by tronghn** [comment]
Personally, I'm against providing support (and thus promoting their continued use) for flows/grants that are widely considered as deprecated/obsolete and goes against current best practices - going as far as the grant being omitted in its entirety in OAuth 2.1.

Then again, this is just a mock server primarily used for testing. While I wish that legacy applications could just be rewritten and updated, that's not always a possibility. If there really is a demand for the support of the ROPC grant out there then I guess it doesn't hurt to add support for it. Though we should probably add a disclaimer or note of some sort to point out that the grant really should be avoided when possible.

**Comment by ybelMekk** [comment]
I agree with what you say @tronghn. Some sort of notation should be possible.

**Comment by tommytroen** [comment]
superseded by #233

**Pull request closed without merging**
