### PR TITLE
feat: introspection_endpoint

### LINKED ISSUE #252: Support mocked introspect endpoint
Seems like it simply returns:

```json
{
  "active": true
}
```

Thanks for considering!

Alt implementation:
https://github.com/axa-group/oauth2-mock-server/blob/2039693d4fb52949b306e257b52d065667970f66/src/lib/oauth2-service.ts#L411-L416

### PR DESCRIPTION
**Pull request by ybelMekk**

### CODE REVIEW

**Comment by patcon** [comment]
Ahhhhh you're the best...! Ok, I'm a little out of my element, but I'll try to sort out how to build and test this.

I expect the approach I'd take is to create a docker container for building feature branches, and then I could upstream that for others like me who wish to try a build from an unpublished feature branch, but don't know much about java.

Does that sound like an OK approach? I'm seeing that you use something called "jib" to build the existing containers (which doesn't use a docker daemon?) and so it seems I'm going a little off-road, but wondering: would this still be useful as a sample `Dockerfile` support file I could upstream? Also, I'm open to suggestions for other ways to make a feature branch available in a `docker-compose.yml` file, like you've generously documented in the README for official releases

**Comment by patcon** [comment]
To be clear, this is how I'm thinking I'd prefer things to work:

```yml
version: '3.7'
services:
  your_app:
    build: .
    ports:
      - 8080:8080
  mock-oauth2-server:
    # Not using this.
    #image: ghcr.io/navikt/mock-oauth2-server:$MOCK_OAUTH2_SERVER_VERSION
    # And instead using this (with example file that might also become available upstream?)
    build: ./support/mock-auth.Dockerfile
    environment:
      MOCK_AUTH_REPO_SLUG: navikt/mock-oauth2-server
      MOCK_AUTH_REPO_BRANCH: introspection_endpoint
    ports:
      - 8080:8080
    hostname: host.docker.internal
```

**Comment by ybelMekk** [comment]
@patcon could you just checkout the bransjen and use build:. ?

**Comment by patcon** [comment]
I don't yet have a simple way to have the whole team using it (since we rely on docker and our dev environment doesn't support building java projects for everyone easily), but I've built it locally and it works for me!

**Comment by ybelMekk** [comment]
@tommytroen 🚤?

**Comment by tommytroen** [comment]
@ybelMekk Looks good! Added a few minor changes.

**Review by tommytroen — APPROVED** [review]

**Comment by patcon** [comment]
Thanks so so much @tommytroen and @ybelMekk 🙏

**Pull request merged**
