### PR TITLE
Support more token signing algos

### LINKED ISSUE #121: Support more token signing algorithms
Hello,

is it possible to support more token signing algorithms? It looks like only RS256 is supported out of the box

### PR DESCRIPTION
**Pull request by ybelMekk**
Ive been taken some choices that may not be in the scope of this issue. 
But its up for discussion.
Ive added support for algos supported by nimbus:   

EC:
    "ES256", 
    "ES384"
    
RSA: 
    "RS256",
     "RS384",
     "RS512",
     "PS256",
     "PS384",
     "PS512"  

Not supported by nibmbus (smoked out with some testing)  "ES256K",   "ES512"

### CODE REVIEW

**Comment by ybelMekk** [comment]
Ive will add some unit test to the KeyGenerator later and pen PR again.

**Comment by Allsimon** [comment]
hello, any news on this PR ? :)

**Comment by tommytroen** [comment]
> hello, any news on this PR ? :)

@Allsimon: sorry about the delay, much of the team has been on vacation. will have a look in the next couple of days.

**Review by tommytroen — APPROVED** [review]
Really good job @ybelMekk 👏  We should consider adding support for `EdDSA` aswell as this could very well be an industry standard once libs support it.

**Review by tronghn — APPROVED** [review]
lgtm

**Comment by ybelMekk** [comment]
good damn. merging

**Pull request merged**
