### PR TITLE
feat: basic client authentication for token exchange grant

### LINKED ISSUE #558: Basic Client Authentication not supported for the Token Exchange Grant
- As pointed out un the [RFC8693](https://www.rfc-editor.org/rfc/rfc8693.html#name-request) the `Token Exchange Request` can be authenticated:
```
" ... using the normal mechanisms provided by OAuth 2.0. [Section 2.3.1](https://www.rfc-editor.org/rfc/rfc6749#section-2.3.1) of [[RFC6749](https://www.rfc-editor.org/rfc/rfc8693.html#RFC6749)] defines password-based authentication of the client, ..."
```

- When performing the request with the `clientId` & `clientSecret` basic auth I'm getting the error:
```
"request must contain a valid client_assertion."
```
- this is likely because it is assumed that the authentication should be of type `JWT`: [OAuth2HttpRequest.kt#L34](https://github.com/navikt/mock-oauth2-server/blob/cb5e0b63f0527cc5b94ad1fb6ea742622a06c163/src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRequest.kt#L34)
- the basic client authentication is present in the request, as debug shows:
image

### PR DESCRIPTION
**Pull request by valdemon**
Solves https://github.com/navikt/mock-oauth2-server/issues/558

### CODE REVIEW

**Review by ybelMekk — APPROVED** [review]
lgtm

**Comment by ybelMekk** [comment]
@valdemon , some lint errors 😄

**Comment by valdemon** [comment]
> @valdemon , some lint errors 😄

yeah, the test title is too long - fixing...

**Comment by valdemon** [comment]
@ybelMekk fix done

**Comment by ybelMekk** [comment]
@tommytroen, any comments?

**Review by tommytroen — APPROVED** [review]
LGTM

**Pull request merged**
