### PR TITLE
fix(OAuth2HttpRequest): smoke out the bug

### PR DESCRIPTION
**Pull request by ybelMekk**
fails with -1. Should ignore and return requested host.

use `SERVER_HOSTNAME`

### CODE REVIEW

**Comment by ybelMekk** [comment]
@tommytroen @jksolbakken i think this could help the issues: https://github.com/navikt/mock-oauth2-server/issues/380 and https://github.com/navikt/mock-oauth2-server/issues/362, but it overrides the ability to set host header, but this seems more legit? 😄

**Comment by tommytroen** [comment]
@ybelMekk Looks ok 👍  However, I prefer not to introduce StandaloneConfig to the OAuth2HttpRequest class, and we should probably rewrite/simplify some of the logic in proxyAwareUrl anyways. I'll have a look to see if this can be solved in another way.

**Comment by ybelMekk** [comment]
> @ybelMekk Looks ok 👍 However, I prefer not to introduce StandaloneConfig to the OAuth2HttpRequest class, and we should probably rewrite/simplify some of the logic in proxyAwareUrl anyways. I'll have a look to see if this can be solved in another way.

agree, looking forward to.

**Comment by tommytroen** [comment]
closing this PR as "the-requesting-domain" is a core feature of the server - changing this to also support static host has too many sideeffects. we can revisit the topic if multiple users have the same usecase: same server on different domains.
#393 is created to do the simplify logic part.

**Pull request closed without merging**
